"""add_compliance_and_audit_models

Revision ID: 95c1f0327ee8
Revises: 09e06454a535
Create Date: 2026-09-08 15:03:22.836673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95c1f0327ee8'
down_revision: Union[str, None] = '09e06454a535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('normative_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('issuing_body', sa.String(length=100), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('current_version', sa.String(length=50), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('url_reference', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['normative_references.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('normative_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_normative_references_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_normative_references_id'), ['id'], unique=False)

    op.create_table('normative_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('version_code', sa.String(length=50), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reference_id'], ['normative_references.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('normative_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_normative_versions_id'), ['id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('VALIDATION_RUN', 'COMPLIANCE_CHECK', 'NORM_UPDATE', 'TEMPLATE_VERSION_CHANGE', 'INSPECTION_COMPLETED', name='auditeventtype'), nullable=False),
    sa.Column('event_detail', sa.JSON(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_inspection_id'), ['inspection_id'], unique=False)

    op.create_table('compliance_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=True),
    sa.Column('compliance_status', sa.Enum('COMPLIANT', 'NON_COMPLIANT', 'WARNING', 'NOT_EVALUATED', name='compliancestatus'), nullable=False),
    sa.Column('normative_ref', sa.String(length=150), nullable=False),
    sa.Column('expected_value', sa.String(length=255), nullable=True),
    sa.Column('actual_value', sa.String(length=255), nullable=True),
    sa.Column('deviation_detail', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('CRITICAL', 'MAJOR', 'MINOR', 'OBSERVATION', name='complianceseverity'), nullable=False),
    sa.Column('validated_at', sa.DateTime(), nullable=False),
    sa.Column('normative_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['checklist_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['normative_version_id'], ['normative_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['response_id'], ['inspection_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_results_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_results_inspection_id'), ['inspection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_results_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_results_response_id'), ['response_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compliance_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_results_response_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_results_item_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_results_inspection_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_results_id'))

    op.drop_table('compliance_results')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_inspection_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_event_type'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('normative_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_normative_versions_id'))

    op.drop_table('normative_versions')
    with op.batch_alter_table('normative_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_normative_references_id'))
        batch_op.drop_index(batch_op.f('ix_normative_references_code'))

    op.drop_table('normative_references')
    # ### end Alembic commands ###
