"""Add components and evidence models

Revision ID: f228caf3e508
Revises: 95c1f0327ee8
Create Date: 2026-09-12 14:42:50.571794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f228caf3e508'
down_revision: Union[str, None] = '95c1f0327ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PANEL_ALARMA', 'POLIDUCTO', 'CILINDRO', 'COMPRESOR', name='componenttype'), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('qr_code', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_components_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_components_qr_code'), ['qr_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_components_serial_number'), ['serial_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_components_type'), ['type'], unique=False)

    op.create_table('inspection_evidences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.Enum('IMAGE', 'VIDEO', name='filetype'), nullable=False),
    sa.Column('storage_url', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['checklist_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspection_evidences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_evidences_id'), ['id'], unique=False)

    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('component_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_inspections_component_id', 'components', ['component_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inspections_component_id', type_='foreignkey')
        batch_op.drop_column('component_id')

    with op.batch_alter_table('inspection_evidences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_evidences_id'))

    op.drop_table('inspection_evidences')
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_components_type'))
        batch_op.drop_index(batch_op.f('ix_components_serial_number'))
        batch_op.drop_index(batch_op.f('ix_components_qr_code'))
        batch_op.drop_index(batch_op.f('ix_components_id'))

    op.drop_table('components')
    # ### end Alembic commands ###
